# Generated by Django 4.0.4 on 2022-05-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_leaves_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='user',
        ),
    ]
