# Generated by Django 4.0.4 on 2022-05-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_leaves_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='reason',
            field=models.TextField(help_text='Brief Reason for leave', max_length=300, verbose_name='Detailed Reason for Leave'),
        ),
    ]
