# Generated by Django 4.0.4 on 2022-05-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_leaves_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='user',
            new_name='referring_user',
        ),
        migrations.AlterField(
            model_name='leaves',
            name='days_count',
            field=models.IntegerField(default=1),
        ),
    ]
