# Generated by Django 4.0.4 on 2022-05-15 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0008_rename_user_leaves_referring_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='referring_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
