# Generated by Django 4.0.4 on 2022-05-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_leaves_referring_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='action_taken',
            field=models.CharField(choices=[('A', 'Accept'), ('B', 'Reject'), ('P', 'Pending')], default='P', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='days_count',
            field=models.IntegerField(),
        ),
    ]
