# Generated by Django 4.0.4 on 2022-05-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_leaves_action_taken_alter_leaves_days_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='action_taken',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending')], default='P', max_length=20),
        ),
    ]
