# Generated by Django 4.0.4 on 2022-05-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_leaves_action_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='action_taken',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
