# Generated by Django 4.0.4 on 2022-05-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_alter_leaves_action_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='action_taken',
            field=models.CharField(choices=[('Accepted', 'Accept'), ('Rejected', 'Reject'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick'), ('Casual Leave', 'Casual Leave'), ('Emergency Leave', 'Emergency'), ('Maternity Leave', 'Maternity'), ('Earned Leave', 'Earned Leave')], max_length=30),
        ),
    ]
