# Generated by Django 4.0.4 on 2022-05-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_leaves_action_taken_alter_leaves_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='action_taken',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
